/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

select *
from start_version_update('1.2', 'Get version detail, by component and by version (or the last one)', _component := 'versions_management');


create or replace function get_version(_component text default 'main', _version text default null)
	returns table
					(
						__version_id         int,
						__version            text,
						__title              text,
						__execution_started  timestamptz,
						__execution_finished timestamptz
					)
	language sql
	cost 1
as
$$

select v.version_id, v.version, v.title, v.execution_started, execution_finished
from __version v
where component = _component
	and ((_version is not null and version = _version)
	or (version_id in (select version_id
										 from __version
										 where component = _component
										 order by created desc
										 limit 1)));
$$;


select *
from stop_version_update('1.2', _component := 'versions_management');
